code = "541715"
name = "Research and Development in the Physical, Engineering, and Life Sciences (except Nanotechnology and Biotechnology)"
sic_correlations = ["3721", "3724", "3728", "3761", "3764", "3769", "8733"]
